[package]
name = "spuzc"
version = "0.1.0"
authors = ["Andrew Stanton-Nurse <andrew@stanton-nurse.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html